version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: simplereads
      POSTGRES_PASSWORD: 05a4379e
      POSTGRES_DB: simplereads
    ports:
      - "5432:5432"